name: Claude Code Review (Disabled - Use Light Version)

on:
  # Disabled to reduce token usage - use claude-review-light.yml instead
  workflow_dispatch: # Manual trigger only

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v0.0.24
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Use Claude Sonnet 4 (latest stable model)
          model: "claude-3-5-sonnet-20241022"

          # Chrome extension specific review prompt
          direct_prompt: |
            このChrome拡張機能のPRをレビューしてください。以下の点に特に注意して確認してください：

            **Chrome拡張機能固有の観点：**
            - Manifest V3の仕様に準拠しているか
            - セキュリティ上の問題（CSP、権限設定など）
            - バックグラウンドスクリプトのサービスワーカー実装
            - コンテンツスクリプトやポップアップスクリプトの実装

            **コード品質：**
            - JavaScriptのベストプラクティス
            - エラーハンドリングの適切性
            - 非同期処理の正しい実装
            - メモリリークの可能性

            **機能面：**
            - ユーザビリティの向上
            - パフォーマンスへの影響
            - 既存機能との互換性

            日本語でフィードバックを提供してください。建設的で具体的な改善提案をお願いします。
